### ISSUE TITLE
Build error: static BUILD_SOURCES_CPIO_GZ

### ISSUE THREAD

**Issue by sts10** [volution/z-tokens#3]
Hello! 

Tried to install z-tokens with `cargo install --bins --git https://github.com/volution/z-tokens --force` just now, and I got the following error toward the end of the build process:

```
Compiling z-tokens v0.1.0 (/home/sschlinkert/.cargo/git/checkouts/z-tokens-387ea9c4306ff871/3768a27/sources)
error: couldn't read ./_embedded/build/sources.cpio.gz: No such file or directory (os error 2)
   --> tools.rs:255:48
    |
255 | static BUILD_SOURCES_CPIO_GZ : &'static [u8] = include_bytes! ("./_embedded/build/sources.cpio.gz");
    |                                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: this error originates in the macro `include_bytes` (in Nightly builds, run with -Z macro-backtrace for more info)

error: could not compile `z-tokens` due to previous error
error: failed to compile `z-tokens v0.1.0 (https://github.com/volution/z-tokens#3768a278)`, intermediate artifacts can be found at `/tmp/cargo-install8XY2Qi`
```

`rustc --version` gives me `rustc 1.66.0 (69f9c33d7 2022-12-12)`, so that should be fine. I'm running Pop_OS 22.04 LTS x86_64 with Kernel: 6.0.12-76060006-generic. 

I got a similar error when I tried `cargo install --bins --tag preview --git https://github.com/volution/z-tokens --force`. Feels like I'm missing a file? Let me know if there's anything else I can try?

**Comment by cipriancraciun** [comment]
Indeed this is a blocking build issue.  However a simple `touch ./_embedded/build/sources.cpio.gz` should solve it, without any other problems.

----

That file, on a release build, contains the actual sources of the tool, so one can run `z-tokens --sources-cpio | gunzip | cpio -i ...` to get them if one wants.  (That's my take on open source.)  :)

**Comment by cipriancraciun** [comment]
It should be fixed right now in both the new `preview` tag and the latest `development` branch.

Thanks for reporting!
